//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class lot
    {
        public long lotID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public decimal currentPrice { get; set; }
        public decimal step { get; set; }
        public decimal blic { get; set; }
        public System.DateTime date { get; set; }
        public int cityID { get; set; }
        public int categoryID { get; set; }
        public int userID { get; set; }
        public int statusID { get; set; }
    }
}
