//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user
    {
        public long userID { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string mail { get; set; }
        public int roleID { get; set; }
        public Nullable<int> vk_userID { get; set; }
        public Nullable<System.DateTime> change_on { get; set; }
    }
}
